project:
  type: website

website:
  title: "Seoyeon's Blog for study"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc/blog/
  sidebar:
    style: "docked"
    search: true
    contents: auto
        
format:
  html:
    theme: 
        light: flatly
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false
    # fontsize: 0.9em